project:
  title: "{{< meta project.title >}}"

format:
  pdf:
    pdf-engine: xelatex
    documentclass: article
    geometry:
      - a4paper
      - left=3cm
      - right=7cm
      - top=2.5cm
      - bottom=2.5cm
    number-sections: false
    toc: true
    toc-depth: 1
    linestretch: 2
    colorlinks: true
    highlight-style: tango
    include-in-header:
      - header.tex
